#!/bin/bash

# The path to the "stable" repository
STABLE_REPO="/opt/undergrad"

# A file listing trusted repositories
TRUSTED_REPOS="$STABLE_REPO/trusted-repos"

# The pattern that unstable/user repository names get passed through where \1 is
# expanded to the name of the repository.
UNSTABLE_PATH="/home/\1/ugrad"

# The user's config file
USER_CONFIG="$HOME/.ugrad"



# Option names for the config file
CONFIG_OPTION_REPOSITORY="repo"


# Repository meta-info filename
REPO_README="repo-readme"

# Repository package index file
REPO_INDEX="repo-index"

# Package meta-info filename
PACKAGE_README="README"

# Package environment setup script
PACKAGE_ENV_SETUP="env-setup"

################################################################################


function error {
	# Display an error. TODO: Make this nicer-looking
	echo "ugrad: $@" 1>&2
}


function fatal {
	# Display an error and exit with the given code.
	err_code="$1"
	shift
	error "$@"
	exit "$err_code"
}


function strip_config_comments {
	# Strip comments out of a config file
	sed -re "s/^([^#]*)(#.*)?$/\1/"
}


function get_config_option {
	# Return only the lines from a config matching a particular option (and remove
	# the option specifier).
	sed -nre "s/^\s*$1\s*=\s*(.*)$/\1/p"
}


function add_config_option {
	# Updates the user's config file, doesn't process std in
	option="$1"
	shift 1
	value="$@"
	
	echo "$option=$value" >> "$USER_CONFIG"
}


function remove_config_option {
	# Updates the user's config file, doesn't process std in
	option="$1"
	shift 1
	value="$@"
	
	# This is a hack as -i on sed is buggy when dealing with bracketed regex
	# sections
	x="$(sed -re "s|^(\s*)$option\s*=\s*$value\s*(#.*)?$|\1\2|" < "$USER_CONFIG")"
	echo -n "$x" > "$USER_CONFIG"
	
	return $?
}


function repo_name_to_path {
	# Convert repository names into their paths using the UNSTABLE_PATH variable
	# as a pattern for repository names which aren't already paths.
	sed -re "s|^([^/].*)$|$UNSTABLE_PATH|" | sed -re "s/^(.*[^/])\/$/\1/"
}


function list_repos {
	# Returns a list of repositories the user is subscribed to.
	(
		echo "$STABLE_REPO"
		cat "$USER_CONFIG" \
			| strip_config_comments \
			| get_config_option "$CONFIG_OPTION_REPOSITORY"
	) | sort | uniq
}


function list_installed_packages {
	# Returns a list of packages the user has installed, or rather, all lines in
	# the config file that aren't settings
	(
		cat "$USER_CONFIG" \
			| strip_config_comments \
			| sed -nre "s/^\s*(([^ \t\n=:]+:|)[^ \t\n=]+)\s*$/\1/p"
	) | sort | uniq
}


function highlight_docstring {
	# Add highlighting to a docstring
	# Commands enclosed in backticks will be highlighted
	
	COMMAND=`echo -en "\e[1m"`
	ARGS=`echo -en "\e[0;32m"`
	RESET=`echo -en "\e[0m"`
	
	sed -re "s/\`(([^\[\`]+)([^\`]*)|)\`/${COMMAND}\2${ARGS}\3${RESET}/g"
}


function package_to_repo {
	# Converts a package name into the repository it is from
	sed -re "s/^((\w+):|)(.*)$/\2/
	         s|^$|$STABLE_REPO|"
}


function package_to_name {
	# Converts a package name into just the name
	sed -re "s/^(\w+:|)(.*)$/\2/"
}


function package_to_path {
	# Convert a package name into the full path to the package's files
	while read arg; do
		echo "$(echo "$arg" \
		        | package_to_repo \
		        | repo_name_to_path)/$(echo "$arg" | package_to_name)"
	done
}


function get_repo_index {
	repo_name_to_path | sed -re "s|^.*$|&/$REPO_INDEX|" | xargs cat
}


################################################################################

function ugrad_help {
	# A documentation system which generates (fetches) documentation from comments
	# left in this source file. The format for this documentation is as follows:
	#
	# Documentation begins with
	#   #DOC#
	# And ends with
	#   #ENDDOC#
	# The first paragraph must be a brief description of the function starting
	# with an unindented line showing the syntax for the command and then followed
	# by indented lines summarising the command. For example:
	#  # mycommand [some args]
	#  #   A brief description of the command.
	#
	# The main documentation for a command should follow the summary after a
	# single empty line.
	#
	# In the main command description unindented lines will be highlighted as
	# commands unless enclosed with backticks.
	
	#DOC#
	# help [command]
	#   Lookup documentation for ugrad commands or list all available commands.
	#
	# Yo dawg,
	#   I put some help in your help so you can get help while you're
	#   getting help.
	#ENDDOC#
	
	(
		if [ -z "$1" ]; then
			echo "ugrad -- The /opt/undergrad Package Manager"
			echo
			echo "Usage: \`ugrad [command]\`"
			echo
			echo "Available Commands:"
			
			# Generate documentation which lists all available commands and a brief
			# introduction.
			
			sed -nre "/^\s*#DOC#\s*$/,/^\s*(#|#ENDDOC#)\s*$/ {
			            /^\s*(#DOC#|#|#ENDDOC#)\s*$/ ! {
			              s/^\s*#\s?//
			              s/^[^ \t]+.*$/\`&\`/
			              s/.*/  &/
			              p
			            }
			          }" "$0"
		else
			# Generate documentation for a given command name
			
			sed -nre "/^\s*#DOC#\s*$/,/^\s*#ENDDOC#\s*$/ {
			              /^\s*#\s*$1\s+.*$/,/^\s*#ENDDOC#\s*$/ {
			              /^\s*(#DOC#|#ENDDOC#)\s*$/ ! {
			                s/^\s*#\s?//
			                s/^[^ \t]+.*$/\`&\`/
			                p
			              }
			            }
			          }" "$0"
		fi;
	) | highlight_docstring 1>&2
}


function ugrad_repo_show {
	# Show information about a repository
	# See ugrad_repo for usage
	
	if [ -z "$1" ]; then
		repo_name="$STABLE_REPO"
	else
		repo_name="$1"
	fi
	
	if ! cd "`echo "$repo_name" | repo_name_to_path 2> /dev/null`"; then
		fatal 1 "Couldn't  enter the repository!"
	elif [ ! -r "$REPO_INDEX" ]; then
		fatal 2 "The repository '$repo_name' could not be found or was not readable."
	fi
	
	# Find out how many packages are available in this repository
	num_avail="$(echo "$repo_name" | get_repo_index | wc -l)"
	
	# Cound how many packages the user has installed from this repository
	num_installed="$(list_installed_packages \
	                 | package_to_repo \
	                 | repo_name_to_path \
	                 | grep -c "`pwd`")"
	
	GREEN="\e[1;32m"
	RED="\e[1;31m"
	RESET="\e[0m"
	
	echo    "Repository:         $repo_name"
	echo    "Location:           `pwd`"
	echo -n "Trusted:            "
		grep -q "`pwd`" "$TRUSTED_REPOS" && echo -e "${GREEN}Yes" || echo -e "${RED}No"
		echo -ne "$RESET"
	echo -n "Subscription:       "
		list_repos | grep -q "$repo_name" && echo "Subscribed" || echo "Not Subscribed"
	echo    "Available Packages: $num_avail"
	echo    "Installed Packages: $num_installed"
	echo    "Last updated:       `stat "$REPO_INDEX" -c "%y"`"
	echo
	cat "$REPO_README"
}


function ugrad_repo {
	#DOC#
	# repo [command]
	#   List/Modify the selection of repositories you want ugrad to search.
	#
	# `Usage:`
	# repo show [repo name]
	#   Show information about the specified repository or if no repository
	#   supplied, the $STABLE_REPO repository.
	# repo list
	#   List the repositories you are subscribed to.
	# repo paths
	#   List the paths of the repositories you are subscribed to.
	# repo path [path]
	#   List the path of the specified repository.
	# repo add [repo name]
	#   Add a repo
	# repo remove [repo name]
	#   Remove a repo
	#ENDDOC#
	command="$1"
	repo_name="$2"
	shift 2
	
	case "$command" in
		add)
			if list_repos | grep -q "$repo_name"; then
				fatal 1 "Repository '$repo_name' already added!"
			elif [ ! -d "`echo "$repo_name" | repo_name_to_path`" ]; then
				fatal 2 "A repository could not be found in" \
				        "`echo "$repo_name" | repo_name_to_path`"
			else
				add_config_option "$CONFIG_OPTION_REPOSITORY" "$repo_name"
			fi
			;;
		remove)
			if list_repos | grep -q "$repo_name"; then
				if ! remove_config_option "$CONFIG_OPTION_REPOSITORY" "$repo_name"; then
					fatal 3 "Could not remove repo, error editing $USER_CONFIG."
				fi
			else
				fatal 4 "Cannot remove unsubscribed repository '$repo_name'."
			fi
			;;
		"paths")
			list_repos | repo_name_to_path;;
		"path")
			echo "$repo_name" | repo_name_to_path;;
		"list")
			list_repos ;;
		"show")
			ugrad_repo_show "$repo_name" ;;
		"")
			fatal -1 "Repo takes at least one argument. See 'ugrad help repo'.";;
		*)
			fatal -1 "Unrecognised command '$command'. See 'ugrad help repo'.";;
	esac
}


function ugrad_show {
	#DOC#
	# show [package name]
	#   Show all known details about a specified package.
	#ENDDOC#
	
	echo "$1" | package_to_path
}


################################################################################


function get_current_repo_path {
	# Returns the path of the repo the shell is currently in
	while [ ! -e "$REPO_README" ]; do
		if ! cd .. 2>&1 > /dev/null; then
			return "$?"
		fi
		if [ "`pwd`" == "/" ]; then
			return 1
		fi
	done
	
	pwd
}


function generate_package_index {
	# Create a package index for the current repository
	# Package indexes consist of 
	
	for package in $(find . -name "$PACKAGE_ENV_SETUP" \
	               | sed -re "s|^[.]/(.*)/$PACKAGE_ENV_SETUP$|\1|"); do
		if [ -e "$package/$PACKAGE_README" ]; then
			# Extract the top line of the readme to add to the index
			readme="`cat "$package/$PACKAGE_README" | head -n 1`"
		else
			readme=""
		fi
		echo "source $package $readme"
	done
}


################################################################################


function ugrad_admin_init {
	# See ugrad_admin docs for usage
	# Initialise the current directory as a repository
	
	# Set the readme
	echo "No information provided." > "$REPO_README"
	
	# Set global-read permissions on the directory
	chmod a+r -R .
	
	echo "Repository created! Don't forget to edit the $REPO_README file."
}


function ugrad_admin_update {
	# See ugrad_admin docs for usage
	# Update the packge repository and permissions.
	if repo_path="`get_current_repo_path`"; then
		cd "$repo_path"
	else
		fatal 1 "Couldn't find a ugrad repository here!"
	fi
	
	# Generate a package-index for the repo
	generate_package_index > "$REPO_INDEX"
	
	# Set global-read permissions on the directory
	chmod a+r -R .
}


function ugrad_admin {
	#DOC#
	# admin [command]
	#   Administration tools for creating/configuring ugrad repositories.
	#
	# admin init
	#   Initialise the current directory as a ugrad repository. This creates an
	#   empty readme and makes the directory world-readable.
	# admin update
	#   Update the current repository's index and set permissions for all files.
	#ENDDOC#
	
	command="$1"
	shift
	
	case "$command" in
		init) ugrad_admin_init "$@";;
		update) ugrad_admin_update "$@";;
		"") fatal 1 "You must give a command, try 'ugrad help admin' for instructions.";;
		*) fatal 2 "Admin command '$command' not recognised.";;
	esac
}


################################################################################


command="$1"
shift 1

case "$command" in
	help) ugrad_help "$@";;
	show) ugrad_show "$@";;
	repo) ugrad_repo "$@";;
	admin) ugrad_admin "$@";;
	"") fatal 1 "You must give a command, try 'ugrad help' for instructions.";;
	*) fatal 2 "Command '$command' not recognised.";;
esac
